### ISSUE TITLE
How do you annotate your papers? What tool do you use?

### ISSUE THREAD

**Issue by humandotlearning** [Machine-Learning-Tokyo/papers-with-annotations#1]
Can you suggest any tool to do annotation on mobile?

**Comment by alisher-ai** [comment]
Thanks for your interest on papers-with-annotations :)  

As for hardware: I use iPad (6th generation) with Apple Pencil (1st generation). 
As for software: I am using Notability (this is a paid app, but it is cheap enough). I am not sure if Notability has mobile app as well. If you check it, could you please let us know :)

**Comment by alisher-ai** [comment]
closing this issue :)

**Comment by kaushal-py** [comment]
I think most of us have this same question. I happened to check this closed issue to find the answer. Can this information be included in the readme?

**Comment by alisher-ai** [comment]
That's a good point. Will include this information to the README. Thank you very much for the heads up.

**Comment by alisher-ai** [comment]
I have added the corresponding information to the README. Thank you for the suggestion!
